# Generated by Django 4.0 on 2021-12-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='counselorsurname',
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='jurysurname',
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='studentsurname',
        ),
        migrations.AlterField(
            model_name='pdf',
            name='studentno',
            field=models.CharField(max_length=50, verbose_name='Öğrenci Numarası'),
        ),
    ]
