# Generated by Django 4.0 on 2021-12-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_delete_user_remove_pdf_counselorsurname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='studenttype',
            field=models.CharField(max_length=50, verbose_name='Öğretim Türü'),
        ),
    ]
