# Generated by Django 4.0 on 2021-12-16 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
